name: Build plugin
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: LSAFlanger-${{ matrix.os }}
          path: build/LSAFlanger_artefacts/Release/VST3
